FROM nginx

ARG MODE

RUN rm /etc/nginx/conf.d/default.conf

COPY nginx.conf /etc/nginx/nginx.conf
COPY conf.d /etc/nginx/conf.d

COPY templates/api_nossl.conf.template /etc/nginx/templates/api_nossl.conf.template
RUN envsubst '\$MODE' < /etc/nginx/templates/api_nossl.conf.template > /etc/nginx/conf.d/api_nossl.conf
