FROM nginx

ARG MODE

RUN rm /etc/nginx/conf.d/default.conf

COPY nginx.conf /etc/nginx/nginx.conf
COPY conf.d /etc/nginx/conf.d

COPY templates/nossl.conf.template /etc/nginx/templates/nossl.conf.template
RUN export MODE=$MODE && envsubst '\$MODE' < /etc/nginx/templates/nossl.conf.template > /etc/nginx/conf.d/nossl.conf
