from models.article import *
from models.article_tag import *
from models.evaluation import *
from models.image import *
from models.review import *
from models.review_tag import *
from models.role import *
from models.scope import *
from models.tag import *
from models.user import *
from models.user_article import *
from models.user_session import *
from models.user_tag import *
from models.verdict import *
from models.verdict_user import *
from models.verdict_tag import *
